name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  awesome-lint:
    strategy:
      fail-fast: false
      matrix:
        files:
          - "readme.md"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: "linting: ${{ matrix.files }}"
        run: npx -y awesome-lint ${{ matrix.files }}
  awesome-bot:
    strategy:
      fail-fast: false
      matrix:
        files:
          - "readme.md"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: "setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: "install awesome-bot"
        run: gem install awesome_bot
      - name: "linting: ${{ matrix.files }}"
        run: awesome_bot --allow-redirect -w https://top.gg/bot ${{ matrix.files }}
